// <auto-generated />
namespace web.railgun.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cat_nameToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cat_nameToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201504121420248_cat_nameToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
